name: game_recordings
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.8
  provider: ^6.0.4
  permission_handler: ^11.3.1

  cupertino_icons: ^1.0.6
  record: ^4.4.4
  audioplayers: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the

flutter:
  uses-material-design: true
